### ISSUE TITLE
Bot Attack

### ISSUE THREAD

**Issue by Azrian0** [pop4959/Stress#4]
Is this plugin able to produce bot attacks on the server? I specifically am looking for a way to stress test x amount of fake players joining all at once.
Plus it would be nice if I can have them all /register and do /rtp so they all load different chunks and see if it crashes.

Love the plugin so far!

**Comment by pop4959** [comment]
No, it currently doesn't have the ability to do this. It isn't really planned right now either because there isn't really any reliable way to spawn in player entities, and it would also be complicated to measure real world performance in that way.

If you do use a separate bot though, you can absolutely use Stress to accurately monitor ticks or TPS for a specific duration as they perform certain actions. See the tests page on the wiki for more information on this.
